name: npm-build-all

on:
  push:
    tags:
      - 'v*' # 发布标签以“v”开头

jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Get latest tag
      id: latest_tag
      run: |
        git fetch --prune --unshallow
        git describe --tags $(git rev-list --tags --max-count=1)
      env:
        GITHUB_TAG: ${{ steps.latest_tag.outputs.stdout }}

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install Dependencies
      run: npm install pnpm -g && pnpm i

    - name: Clean build directory
      run: rm -rf build/*

    - name: Build
      run: pnpm run build:all

    - name: Install zip
      run: sudo apt-get install zip

    - name: Compress and Rename
      run: |
        for subdir in build/*; do
          if [ -d "$subdir" ]; then
            # Compress and rename the subdirectory
            # cd "$subdir" && zip -r "../$(basename "$subdir")-$GITHUB_TAG.zip" . && cd ..
            zip -r -9 "$subdir.zip" "$subdir"
            mv "$subdir.zip" "${subdir}-$GITHUB_TAG.zip"
          fi
        done

    # 将要发布的文件作为 artifact 上传到 GitHub
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: extensionsZip
        path: build/*.zip