name: npm-build-all

on:
  push:
    tags:
      - 'v*' # 发布标签以“v”开头

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get Git tag
      id: get_tag
      run: echo "::set-output name=tag::$(git describe --tags --abbrev=0)"
    - name: Get version from Git tag
      id: get_version
      run: echo "::set-output name=version::${{ steps.get_tag.outputs.tag }}"

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'

    - name: Install Dependencies
      run: npm install pnpm -g && pnpm i

    - name: Clean dist directory
      run: rm -rf dist/*

    - name: Build
      run: pnpm run build

    - name: Install gzip
      run: sudo apt-get install gzip

    - name: Install zip
      run: sudo apt-get install zip

    - name: Compress and Rename
      run: |
        for subdir in dist/*; do
          if [ -d "$subdir" ]; then
            # Compress and rename the subdirectory
            # cd "$subdir" && zip -r "../$(basename "$subdir")-${{ steps.get_version.outputs.version }}.zip" . && cd ..
            zip -r -9 "$subdir.zip" "$subdir"
            mv "$subdir.zip" "${subdir}${{ steps.get_version.outputs.version }}.zip"
          fi
        done

    # 将要发布的文件作为 artifact 上传到 GitHub
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: extensionsZip
        path: build/*.zip