name: GitHub Release

on:
  push:
    tags:
      - "v*" # 发布标签以“v”开头

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Query version number
        run: echo "version=${GITHUB_REF:11}" >> $GITHUB_ENV

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
      - run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build:all

      - name: Install zip
        run: sudo apt-get install zip

      - name: Compress and Rename
        run: |
          for subdir in build/*; do
            if [ -d "$subdir" ]; then
              zip -r -9 "$subdir.zip" "$subdir"
              mv "$subdir.zip" "${subdir}-${{ env.version }}.zip"
            fi
          done
      - name: echo file
        run: |
          echo "build file"
          for file in build/*; do
            if [ -f "$file" ]; then
              echo "$file"
            fi
          done
          
      - name: Create Release
        uses: softprops/action-gh-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.version }}
          name: ChatGPT ${{ env.version }}
          body: See the assets to download this version and install.
          prerelease: false
          generate_release_notes: false
          files: ./build/*.zip
