name: GitHub Release

on:
  push:
    tags:
      - "v*" # 发布标签以“v”开头

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # - name: Get latest tag
      #   id: latest_tag
      #   run: |
      #     git fetch --tags --prune
      #     git describe --tags $(git rev-list --tags --max-count=1)
      #   env:
      #     GITHUB_TAG: ${{ steps.latest_tag.outputs.stdout }}

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        # run: echo "{VERSION}={VERSION}" >> ${GITHUB_REF/refs\/tags\//}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Echo Version
        run: echo ${{ steps.get_version.outputs.VERSION }}

      - name: Install Dependencies
        run: npm install pnpm -g && pnpm i

      - name: Clean build directory
        run: rm -rf build/*

      - name: Build
        run: pnpm run build:all

      - name: Install zip
        run: sudo apt-get install zip

      - name: Compress and Rename
        run: |
          for subdir in build/*; do
            if [ -d "$subdir" ]; then
              # Compress and rename the subdirectory
              # cd "$subdir" && zip -r "../$(basename "$subdir")-${{ steps.get_version.outputs.VERSION }}.zip" . && cd ..
              zip -r -9 "$subdir.zip" "$subdir"
              mv "$subdir.zip" "${subdir}-${{ steps.get_version.outputs.VERSION }}.zip"
            fi
          done
      - name: echo file
        run: |
          echo "目录下文件名："
          for file in *; do
            if [ -f "$file" ]; then
              echo "$file"
            fi
          done
      # 将要发布的文件作为 artifact 上传到 GitHub
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: extensionsZip
          path: path/build/*.zip

  release:
    runs-on: ubuntu-latest
    permissions: write-all
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      # 下载 npm-build 工作流程的 artifact
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: extensionsZip
          path: path/build/
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: build/

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
          body: "Release of version ${{ steps.get_version.outputs.VERSION }}"
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/*
          asset_name: build
          asset_content_type: application/zip
